spring.application.name=ems

# database
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# security
# spring.security.user.name=admin
# spring.security.user.password=4111

# server details
server.servlet.context-path = /api/dev/ems

logging.level.org.springframework.security=info

frontend.url=${FRONTEND_BASE_URL}