spring.application.name=ems

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=4111
spring.jpa.hibernate.ddl-auto=update

# security
# spring.security.user.name=admin
# spring.security.user.password=4111

